"""empty message

Revision ID: 17028787f7fe
Revises: 47932bd436fe
Create Date: 2021-04-11 15:00:10.397610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17028787f7fe'
down_revision = '47932bd436fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'looking_for_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('looking_for_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
