"""empty message

Revision ID: 47932bd436fe
Revises: 6829a97e8c7d
Create Date: 2021-04-11 14:45:59.548968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47932bd436fe'
down_revision = '6829a97e8c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
