"""empty message

Revision ID: 6829a97e8c7d
Revises: 5e9631de1b27
Create Date: 2021-04-11 13:50:35.194993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6829a97e8c7d'
down_revision = '5e9631de1b27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('looking_for_venue', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('seeking_description', sa.String(length=300), nullable=True))
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website_link')
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'looking_for_venue')
    # ### end Alembic commands ###
