"""empty message

Revision ID: bcb4c2f31658
Revises: 17028787f7fe
Create Date: 2021-04-11 15:03:51.814754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcb4c2f31658'
down_revision = '17028787f7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_descriptions', sa.String(length=300), nullable=True))
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_descriptions')
    # ### end Alembic commands ###
